language: ruby
rvm:
  - 1.9.3
notifications:
  email:
    - zach@zachholman.com
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtag1-dev mpd mpc ffmpeg
before_script:
  - mv test/play.yml config
  - mysql -e 'create database play_test;'
  - bundle exec rake db:migrate